package com.workmotion.state_enum;


public enum EmployeeEvents {

	IN_CHECK, WORK_PERMIT_FINISH ,SECURITY_FINISH, FINAL_APPROVE,WORK_PERMIT_VERIFY,
	REJECT_ADDED, REJECT_WORK_PERMIT ,REJECT_SECURITY_CHECK, FINAL_REJECT
}
