package com.workmotion.state_enum;

public enum EmployeeStates {
	ADDED , IN_CHECK , APPROVED , ACTIVE ,
	
	FORK, JOIN, // will use them for fork and join
	SECURITY_CHECK_STARTED, WORK_PERMIT_CHECK_STARTED,SECURITY_CHECK_FINISHED, WORK_PERMIT_CHECK_FINISHED,WORK_PERMIT_CHECK_VERIFIED,
	
	REJECTED
	
}
